Parameters:
  EnvironmentSize:
    Type: String
    Default: SMALL
    AllowedValues:
      - SMALL
      - MEDIUM
      - LARGE
    Description: Select Environment Size (S,M,L)
  DatabaseName:
    Type: String
    Default: wordpress
  DatabaseUser:
    Type: String
    Default: wordpress
  DatabasePassword:
    Type: String
    Default: w0rdpr355
    NoEcho: true
Mappings:
  RegionMap:
    us-east-1:
      AMALINUX: ami-0fc61db8544a617ed
    us-east-2:
      AMALINUX: ami-0e01ce4ee18447327
    us-west-1:
      AMALINUX: ami-09a7fe78668f1e2c0
    us-west-2:
      AMALINUX: ami-0ce21b51cb31a48b8
    sa-east-1:
      AMALINUX: ami-0b032e878a66c3b68
    ca-central-1:
      AMALINUX: ami-0bf54ac1b628cf143
    eu-west-1:
      AMALINUX: ami-04d5cc9b88f9d1d39
    eu-west-2:
      AMALINUX: ami-0cb790308f7591fa6
    eu-west-3:
      AMALINUX: ami-07eda9385feb1e969
    eu-north-1:
      AMALINUX: ami-0f630db6194a81ad0
    eu-central-1:
      AMALINUX: ami-0ec1ba09723e5bfac
    ap-southeast-1:
      AMALINUX: ami-0cbc6aae997c6538a
    ap-southeast-2:
      AMALINUX: ami-08fdde86b93accf1c
    ap-northeast-1:
      AMALINUX: ami-052652af12b58691f
    ap-northeast-2:
      AMALINUX: ami-0db78afd3d150fc18
    ap-south-1:
      AMALINUX: ami-03b5297d565ef30a6
  InstanceSize:
    SMALL:
      "EC2" : "t2.micro"
      "DB" : "db.t2.micro"
    MEDIUM:
      "EC2" : "t2.small"
      "DB" : "db.t2.small"
    LARGE:
      "EC2" : "t2.medium"
      "DB" : "db.t2.medium"
Resources:
  DB:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: 5
      StorageType: gp2
      DBInstanceClass: !FindInMap [InstanceSize, !Ref EnvironmentSize, DB] # Dynamic mapping + Pseudo Parameter
      DBName: !Ref DatabaseName
      Engine: MySQL
      MasterUsername: !Ref DatabaseUser
      MasterUserPassword: !Ref DatabasePassword
  EC2:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMALINUX] # Dynamic mapping + Pseudo Parameter
      InstanceType: !FindInMap [InstanceSize, !Ref EnvironmentSize, EC2]
      KeyName: AdvancedCFN
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash
            yum update -y
            amazon-linux-extras install -y php7.2 # If php is not installed, run the command in EC2 terminal
            yum install -y httpd
            systemctl start httpd
            systemctl enable httpd
            cd /var/www/html
            wget https://wordpress.org/latest.tar.gz
            tar -xzf latest.tar.gz
            cp -r wordpress/* /var/www/html/
            rm -rf wordpress
            rm -rf latest.tar.gz
            chmod -R 755 wp-content
            chown -R apache:apache wp-content
            cp wp-config-sample.php wp-config.php
            sed -i 's/database_name_here/${DatabaseName}/g' wp-config.php
            sed -i 's/localhost/${DB.Endpoint.Address}/g' wp-config.php
            sed -i 's/username_here/${DatabaseUser}/g' wp-config.php
            sed -i 's/password_here/${DatabasePassword}/g' wp-config.php
  S3:
    Type: "AWS::S3::Bucket"
